modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
[[mods]]
modId="krystalsmaterialcompats"
version="${file.jarVersion}"
displayName="Krystal's Material Compats"
logoFile="krystalsmaterialcompats.png"
credits="Thanks for this example mod goes to Java"
authors="Love, Cheese and small house plants"
description='''
'''
[[dependencies.krystalsmaterialcompats]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.krystalsmaterialcompats]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
